version: '3.8'

services:
  eco-server:
    image: ghcr.io/gameservermanagers/gameserver:eco
    container_name: eco-server
    restart: unless-stopped
    ports:
      - "3010:3000/tcp"
      - "3011:3001/udp"
    environment:
      - POST_INSTALL_CHOWN=true
      - PUID=1000
      - PGID=1000
    volumes:
      - eco_data:/home/linuxgsm/serverfiles

volumes:
  eco_data:
